services:
  web:
    build: .                # ⬅️ usa o Dockerfile recém-criado
    container_name: web_thermosafe
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html    # mantém o mapeamento do seu projeto
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_thermosafe
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_thermosafe
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"

volumes:
  db_data:
